### ISSUE TITLE
support `view` action type

### ISSUE THREAD

**Issue by Yaiba** [kwilteam/kuneiform#13]
Add support for `view` action type, e.g. `action list_user() public view`, this will mark the action as a read-only action

These need to be done:
- [x] kwilteam/kwil-db#135
- [x] kwilteam/kwil.py#3
- [ ] kwilteam/kwil-js#11

**Comment by brennanjl** [comment]
Checking in @KwilLuke @Yaiba that this got included in the recent JS SDK pre-release.  I believe it did.  If so, we should close @KwilLuke

**Comment by KwilLuke** [comment]
Yep, we decided on the must_sign keyword, which is working in the current kwil-js pre-release.
